# These are supported funding model platforms

github: [mukeshmithrakumar]
patreon: adhiraiyan
liberapay: mmukesh
custom: https://www.buymeacoffee.com/mmukesh
custom: https://paypal.me/mukeshmithrakumar
